namespace AIDecisionCenter.Core.Models;

public sealed record TaskMessage(
    long Id,
    string ExternalId,
    string Source,
    string? SourceRunId,
    string Project,
    string? TaskKey,
    TimeOnly Slot,
    string TaskType,
    DateOnly ScheduledDate,
    DateTimeOffset ScheduledFor,
    DateTimeOffset CompletedAt,
    DateTimeOffset ReceivedAt,
    TaskMessageStatus Status,
    string? RegistryId,
    string? ProtocolId,
    string Summary,
    string BodyMarkdown,
    string PayloadJson,
    string ContentSha256,
    bool IsRead,
    bool IsStarred,
    bool IsArchived,
    string Note);
